/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.23).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Artist;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-11-27T14:24:09.910Z[GMT]")
public interface ArtistApi {

    @Operation(summary = "Create artist", description = "Cretes an unexisting artist.", tags={ "Artist" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation") })
    @RequestMapping(value = "/Artist",
        consumes = { "*/*" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> createArtist(@Parameter(in = ParameterIn.DEFAULT, description = "Created artist object", required=true, schema=@Schema()) @Valid @RequestBody Artist body);


    @Operation(summary = "Delete artist", description = "Delete artist object", tags={ "Artist" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid artist name supplied"),
        
        @ApiResponse(responseCode = "404", description = "Artist not found") })
    @RequestMapping(value = "/Artist/{artistName}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteArtist(@Parameter(in = ParameterIn.PATH, description = "The name that needs to be deleted", required=true, schema=@Schema()) @PathVariable("artistName") String artistName);


    @Operation(summary = "Get artist by artist name", description = "", tags={ "Artist" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(schema = @Schema(implementation = Artist.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid artist name supplied"),
        
        @ApiResponse(responseCode = "404", description = "Artist not found") })
    @RequestMapping(value = "/Artist/{artistName}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Artist> getArtistByName(@Parameter(in = ParameterIn.PATH, description = "The name that needs to be fetched.", required=true, schema=@Schema()) @PathVariable("artistName") String artistName);

}

